apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-deployment
  labels:
    app: my-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
        - name: my-app
          image: maevasyntiche/my-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: watchlistdb
            - name: DB_USER
              value: watchlistuser
            - name: DB_PASSWORD
              value: watchlistpassword
            - name: DB_HOST
              value: postgresql-service
            - name: DB_PORT
              value: "5432"